name: Build APK Android

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: stable
          cache: true

      - name: Find Flutter project
        shell: bash
        run: |
          PROJECT_DIR=$(dirname "$(find . -name pubspec.yaml -type f | head -n 1)")

          if [ -z "$PROJECT_DIR" ]; then
            echo "pubspec.yaml tidak ditemukan!"
            exit 1
          fi

          echo "PROJECT_DIR=$PROJECT_DIR" >> "$GITHUB_ENV"
          echo "Project directory: $PROJECT_DIR"

      - name: Flutter Pub Get
        run: |
          cd "$PROJECT_DIR"
          flutter clean
          flutter pub get

      - name: Build APK
        run: |
          cd "$PROJECT_DIR"
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: YPM-Talang-Jawa-APK
          path: "**/build/app/outputs/flutter-apk/app-release.apk"
          if-no-files-found: error
